- hosts: security_group_launch-wizard-42
  become: true
  tasks:
  - name: Removing previous code
    file:
      path: /var/www/html/website
      state: absent
  - git:
      repo: https://github.com/Riyaz1994/website.git
      dest: /var/www/html/website
